# Generated by Django 4.1.7 on 2023-03-13 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CRECHE', 'CRECHE'), ('PRE_NUR', 'PRE NURSERY'), ('NUR1', 'NURSERY 1'), ('NUR2', 'NURSERY 2'), ('NUR3', 'NURSERY 3'), ('PRI1', 'PRIMARY 1'), ('PRI2', 'PRIMARY 2'), ('PRI3', 'PRIMARY 3'), ('PRI4', 'PRIMARY 4'), ('PRI5', 'PRIMARY 5'), ('PRI6', 'PRIMARY 6'), ('JSS1', 'JUNIOR SECONDARY SCHOOL 1'), ('JSS2', 'JUNIOR SECONDARY SCHOOL 2'), ('JSS3', 'JUNIOR SECONDARY SCHOOL 3'), ('SSS1', 'SENIOR SECONDARY SCHOOL 1'), ('SSS2', 'SENIOR SECONDARY SCHOOL 2'), ('SSS3', 'SENIOR SECONDARY SCHOOL 3')], max_length=150, unique=True, verbose_name='Class Name')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('FT', '1ST Term'), ('ST', '2ND Term'), ('TT', '3RD Term')], help_text='term for this report eg. 1st Term', max_length=200)),
                ('year', models.CharField(max_length=5)),
                ('session', models.CharField(max_length=200)),
                ('grading', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.class')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.reportclass')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='subject name')),
                ('for_all_class', models.BooleanField(default=False, help_text='is this subject for all class', verbose_name='for all class')),
                ('klass', models.ForeignKey(help_text="you should'nt be seeing this", null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.class', verbose_name='class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Name of student', max_length=200, verbose_name='student name')),
                ('last_name', models.CharField(blank=True, default='', help_text='Surname of student', max_length=200, null=True, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, default='', help_text='Other name', max_length=200, null=True, verbose_name='middle name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('admission_no', models.CharField(blank=True, editable=False, max_length=100, verbose_name='admission no')),
                ('serial_no', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Serial no')),
                ('phone_no', models.CharField(default='+123', max_length=50, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, verbose_name='gender')),
                ('created_when', models.DateField(auto_now_add=True, verbose_name='when field was created')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Registration date')),
                ('address', models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='Address')),
                ('headshot', models.ImageField(null=True, upload_to='media/student_headshots', verbose_name='profile photo')),
                ('was_created', models.BooleanField(default=False, editable=False, help_text='check if this object was fully created, stuff like admission_no do not need to be regenerated when this returns True', verbose_name='Was created')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.class', verbose_name='class')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.PositiveIntegerField(null=True)),
                ('project', models.PositiveIntegerField(null=True)),
                ('exam', models.PositiveIntegerField(null=True)),
                ('rep_stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.reportstudent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.subject')),
            ],
        ),
        migrations.AddField(
            model_name='reportstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student'),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='full_name')),
                ('relationship', models.CharField(choices=[('GD', 'Guardian'), ('MT', 'Mother'), ('FT', 'Father'), ('UN', 'Uncle'), ('AT', 'Aunty'), ('BR', 'Brother'), ('ST', 'Sister'), ('GRDFT', 'Grand Father'), ('GRDMT', 'Grand Mother')], default='GD', max_length=50, verbose_name='Relationship with child')),
                ('phone_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, verbose_name='gender')),
                ('address', models.CharField(blank=True, default='', max_length=3500, null=True, verbose_name='Address')),
                ('occupation', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Address')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student', verbose_name='child of this gaurdian')),
            ],
        ),
    ]
